apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.my-apps.tap.20240805010111.0.0+build.6aff574
spec:
  refName: where-for-dinner-search.my-apps.tap
  version: 20240805010111.0.0+build.6aff574
  releaseNotes: |
    Release v20240805010111.0.0+build.6aff574 of package where-for-dinner-search.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/tap-ci/ci-pipeline/apps-04-08-2024-14-43-28-125063513/where-for-dinner-search-my-apps-bundle@sha256:5b855f224a764820e707e4718941614fc78f5bc2c0c389a355544a1a81688731
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

